services:
  - type: web
    name: cleanpc
    env: docker
    repo: https://github.com/lotex08/cleanpc
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        value: sqlite:///./cleanpc.db
    healthCheckPath: /api/health
